### ISSUE TITLE
use of the spm_opm_sim

### ISSUE THREAD

**Issue by qishengjie9** [tierneytim/OPM#15]
hello, when I simulate magnetometer data with the function "spm_opm_sim", I can not use the MEG object generated as your tutorial to simulate the MEG source in the matlabbatch environment. The error is "no executable modules, but still unresolved dependencies or incomplete module inputs". I wonder if I miss any steps before the simulation of sources in the matlabbatch. Thanks for your help!

**Comment by tierneytim** [comment]
Hi,

Can you post the code you are using and a screenshot of the batch (or the batch code)? I then can try to reproduce this issue and fix it.

**Comment by qishengjie9** [comment]
I am so sorry！ I find there is a problem with the code I wrote. Now it can run successfully.
Thanks for your kind help!

**Comment by tierneytim** [comment]
wonderful! best of luck with your research
