### ISSUE TITLE
Mark bad channals when channel names overlapped 

### ISSUE THREAD

**Issue by ZQInQAAS** [tierneytim/OPM#18]
Hi, I got a problem when I try to mark bad channals of my own data during use spm_opm_hfc.m，Because my channal names have some overlap，such as 'CH1' and 'CH12'，so I try to use codes
`  [indsRem, ~] = match_str(s.label, badLabels); `  
to replace 
` indsRem = [];`
` for i =1:length(badLabels)`
`     indsRem=[indsRem strmatch(badLabels{i},s.label)];`
` end`
in spm_opm_hfc.m to solve this problem.
where the function match_str() is from ` \toolbox\spm12\external\fieldtrip\utilities\match_str.m` .

By the way, when I applied HFC on my own opm data, I found the results are exactly the same when I change the order (S.L). 
I wonder if it is because my data only have one axis?  
And I set S.balance=0 since I don't have an MRI data, I don't know how much does that affect the outcome.

**Comment by tierneytim** [comment]
Hi, I'll have a look at the naming issue. Sounds like a bug. Can you post the code you used to check for numerical equivalence when changing S.L? These results can be very similar for a number of reasons but are unlikely to be identical unless there is a bug or your array can't distinguish between fields and gradients.

**Comment by ZQInQAAS** [comment]
Oh, sorry, I fixed some error in my codes. Afterthat I got the results here:
![1681453518699](https://user-images.githubusercontent.com/30070547/231961568-e1e8633a-4037-4429-ab1f-daa567a3f533.jpg)
It seems unexpected, have you ever met this kind of problem?

**Comment by tierneytim** [comment]
These results are to be expected. There are two problems here. The first is statistical and the second is physical.

The statistical problem is that the first four orders of harmonics require 3,8,15 and 24 regressors respectively. As you have a small number of channels you will explain a lot of variability by chance with low channel systems.

The second problem is that even for large channel systems single axis systems are not good at distinguishing between brain signal and interference which is also why the amplitude is decreasing.

Ultimately,one should only use higher order harmonics with large channel number, multiaxis systems

**Comment by ZQInQAAS** [comment]
Now I know it. Thank you so much~
