### ISSUE TITLE
ICA for SPM

### ISSUE THREAD

**Issue by neurofractal** [tierneytim/OPM#4]
# Let's get some ICA working for SPM:

### Example Fieldtrip Code for OPMs
https://gist.github.com/neurofractal/146823ec8c9105a7287ad3bb8b5babc1

Currently finding it best to provide a TAN-only layout for easier interpretation of components

### **fastica** 
- Extra functions required in SPM: https://github.com/fieldtrip/fieldtrip/tree/master/external/fastica
- ft_componentanalysis checks for the fastica scripts using ft_hastoolbox on line 501

### **runica** 
- Extra function required in SPM: https://github.com/fieldtrip/fieldtrip/blob/master/external/eeglab/runica.m (seems to be ONLY this script required rather than the whole folder)
- ft_componentanalysis checks for the fastica scripts using ft_hastoolbox on line 535

### **Plotting** 
For simple plotting of independent components:
```matlab
cfg.viewmode = 'component';
ft_databrowser(cfg, comp)
```
For fancier plotting see: i) [ft_icabrowser](https://github.com/fieldtrip/fieldtrip/blob/master/contrib/misc/ft_icabrowser.m) (though I found this buggy) ii) Rob's [tutorial script 2](https://github.com/FIL-OPMEG/tutorials_interference/blob/5137b03d791b540b114e26e5f664a345e7262638/pipeline_tutorial_2.m#L238) for custom code

**Comment by neurofractal** [comment]
CC @RCTimms

**Comment by neurofractal** [comment]
https://github.com/OHBA-analysis/osl-core/blob/master/africa/osl_africa.m

**Comment by tierneytim** [comment]
First implementation done
